name: Check backend code with ESLint and Prettier
on:
  pull_request:
  push:
jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checks out the latest Git commit
        uses: actions/checkout@v4
      - name: Sets up a Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npx eslint src/**/*.ts
      - run: npx tsc --noemit
      - run: npx prettier "src/**/*.ts"