name: Check frontend code with ESLint and Prettier
on:
  pull_request:
  push:
jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checks out the latest Git commit
        uses: actions/checkout@v4
      - name: Sets up a Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npx eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0
      - run: npx tsc --noemit
      - run: npx prettier "src/**/*.{ts,tsx,js,jsx,json,css,scss,md}"