name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: alderland/testing-and-typescript-school
        env:
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --name some-postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Set up database credentials
      env:
        PGURI: ${{ secrets.PGURI }}
      run: |
        echo "PGURI=${PGURI}" >> $GITHUB_ENV

    - name: Install and start backend server
      run: |
        cd backend
        npm ci
        npm run build
        node dist/index.js &
        sleep 5

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        project: frontend
        working-directory: frontend
        browser: chrome
        build: npm run build
        start: npm run preview
        wait-on: 'http://localhost:5173'
        config-file: cypress.config.ts